version: '3'

services:
###########
# Traefik #
###########
  traefik:
    image: traefik
    container_name: proxy_traefik
    restart: unless-stopped
    hostname: traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.%DOMAIN%
      - traefik.frontend.auth.basic=%VAR%
      - traefik.port=8080
      - traefik.docker.network=traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - %TRAEFIK%traefik.toml:/traefik.toml:ro
      - %TRAEFIK%letsencrypt/certs:/etc/traefik/acme:rw
      - /var/log/traefik:/var/log
    ports:
      - "80:80"
      - "443:443"
    command:
      - --web
      - --accessLog.filePath=/var/log/access.log
      - --accessLog.filters.statusCodes=400-499
    networks:
      - proxy

  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: "ftp"
    restart: unless-stopped
    volumes:
      - %TRAEFIK%pure-ftp:/etc/pure-ftpd/passwd
      - /home:/home/ftpusers
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: traefik_proxy
