---
- hosts: localhost
  gather_facts: false

  tasks:

    - name: Create status directory if needed
      file:
        path: "{{ settings.storage }}/status"
        state: directory
        mode: "0775"

    - name: Create watchtower state
      shell: |
        echo "1" > "{{ settings.storage }}/status/watchtower"

    - name: Deploy watchtower
      docker_container:
        name: 'watchtower'
        image: 'containrrr/watchtower:latest'
        pull: yes
        command: '--cleanup --schedule "0 0 4 * * *"'
        state: started
        restart_policy: unless-stopped
        env:
          DOCKER_API_VERSION: '1.52'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
        networks:
          - name: traefik_proxy

    - name: Insert watchtower into database
      shell:
        cmd: |
          sqlite3 {{ settings.source }}/ssddb << EOF
              REPLACE INTO applications (name,status,subdomain,port)
              VALUES
              ('watchtower',2,'',0);
          EOF
