#!/bin/bash

source /opt/seedbox-compose/includes/functions.sh
source /opt/seedbox-compose/includes/variables.sh

## mise à jour du git
#rm -rf /opt/seedbox-compose > /dev/null 2>&1
#git clone https://github.com/laster13/patxav.git /opt/seedbox-compose

## Mise à jour du systeme
update_system

## suppression traefik
docker rm -f traefik > /dev/null 2>&1
rm -rf /opt/seedbox/docker/traefik

## supression portainer
docker rm -f portainer > /dev/null 2>&1
rm -rf /opt/seedbox/docker/portainer

## cloudflare
cloudflare

## reinstallation traefik, portainer
install_traefik
install_portainer

## reinstallation application
SERVICESPERUSER="$SERVICESUSER$SEEDUSER"
SEEDUSER=$(cat /opt/seedbox/variables/users)
while read line; do echo $line | cut -d'.' -f1; done < /home/$SEEDUSER/resume > $SERVICESUSER$SEEDUSER
mv /home/$SEEDUSER/resume /tmp
install_service
mv /tmp/resume /home/$SEEDUSER/
rm $SERVICESUSER$SEEDUSER
