#!/bin/bash

## récupération des variables

mkdir -p /opt/seedbox/variables
SEEDUSER=$(cat /opt/seedbox/users)
echo $SEEDUSER > "/opt/seedbox/variables/users"
USERID=$(id -u $SEEDUSER)
GRPID=$(id -g $SEEDUSER)
echo $USERID > "/opt/seedbox/variables/userid"
echo $GRPID > "/opt/seedbox/variables/groupid"
DOMAIN=$(whiptail --title "Votre nom de Domaine" --inputbox \
"Merci de taper votre nom de Domaine (exemple: nomdedomaine.fr) :" 7 50 3>&1 1>&2 2>&3)
echo $DOMAIN > "/opt/seedbox/variables/domain"
CONTACTEMAIL=$(whiptail --title "Adresse Email" --inputbox \
"Merci de taper votre adresse Email :" 7 50 3>&1 1>&2 2>&3)
echo $CONTACTEMAIL > "/opt/seedbox/variables/mail"
GROUPE=$(cat /opt/seedbox/group)
echo $GROUPE > "/opt/seedbox/variables/group"

## Mise en variables des remotes
REMOTE=$(grep -iC 4 "token" /root/.config/rclone/rclone.conf | head -n 1 | sed "s/\[//g" | sed "s/\]//g")
REMOTEPLEX=$(grep -iC 2 "/mnt/plexdrive" /root/.config/rclone/rclone.conf | head -n 1 | sed "s/\[//g" | sed "s/\]//g")
REMOTECRYPT=$(grep -v -e $REMOTEPLEX -e $REMOTE /root/.config/rclone/rclone.conf | grep "\[" | sed "s/\[//g" | sed "s/\]//g" | head -n 1)
echo $REMOTEPLEX > /opt/seedbox/variables/remoteplex
echo $REMOTECRYPT > /opt/seedbox/variables/remote

#modification du fichier resume
rm /home/$SEEDUSER/resume

# rename actifs containers
docker ps --format '{{.Names}}' > /home/$SEEDUSER/list
for line in $(cat /home/$SEEDUSER/list | cut -d '-' -f1)
do
if [ "$line" != "traefik" ] && [ "$line" != "portainer" ] && [ "$line" != "watchtower" ]; then
echo $line.$DOMAIN >> /home/$SEEDUSER/resume
cp /opt/seedbox-compose/includes/dockerapps/$line /opt/seedbox/conf/$line
docker rename $line-$SEEDUSER $line
fi
done
rm /home/$SEEDUSER/list
rm /opt/seedbox/group
rm /opt/seedbox/plex.pt
rm /opt/seedbox/ports.pt
rm /opt/seedbox/ports1.pt
rm /opt/seedbox/ports2.pt
rm /opt/seedbox/resume
rm /opt/seedbox/users