#!/bin/bash
docker run -it --rm \
   -v /home/%SEEDUSER%/local/rutorrent:/home/%SEEDUSER%/local/rutorrent \
   -v /opt/seedbox/docker/%SEEDUSER%/rutorrent/sock:/run/php \
   magicalex/rtorrent-cleaner
echo ""
docker run -it --rm \
   -v /home/%SEEDUSER%/local/rutorrent:/home/%SEEDUSER%/local/rutorrent \
   -v /opt/seedbox/docker/%SEEDUSER%/rutorrent/sock:/run/php \
   magicalex/rtorrent-cleaner $* /run/php/rtorrent.sock
