#!/bin/bash

docker run -it --rm \
   -v /home/%SEEDUSER%/local/rutorrent:/home/%SEEDUSER%/local/rutorrent \
   -v /run/php:/run/php \
   magicalex/docker-rtorrent-cleaner
echo ""
docker run -it --rm \
   -v /home/%SEEDUSER%/local/rutorrent:/home/%SEEDUSER%/local/rutorrent \
   -v /run/php:/run/php \
   magicalex/docker-rtorrent-cleaner --scgi=/run/php/.rtorrent.sock $*
