#!/bin/bash

docker run -it --rm \
   -v /home/%SEEDUSER%/local/rutorrent:/home/%SEEDUSER%/local/rutorrent \
   -v /run/php:/run/php \
   magicalex/rtorrent-cleaner
echo ""
docker run -it --rm \
   -v /home/%SEEDUSER%/local/rutorrent:/home/%SEEDUSER%/local/rutorrent \
   -v /run/php:/run/php \
   magicalex/rtorrent-cleaner $*
