#!/bin/bash

source includes/functions.sh
source includes/variables.sh

echo ""
echo -e "${CCYAN}#########################################################${CEND}"
echo ""
echo -e "${CCYAN}          DEMARRAGE DU SCRIPT DE MISE A JOUR              ${CEND}"
echo ""
echo -e "${CCYAN}#########################################################${CEND}"
echo ""

echo -e "${BLUE}### Récupération des variables ###${NC}"
echo ""

echo -e "\nAppuyer sur ${CCYAN}[ENTREE]${CEND} pour continuer..."
read -r

mkdir -p /opt/seedbox/variables
SEEDUSER=$(cat /opt/seedbox/users)
echo $SEEDUSER > "/opt/seedbox/variables/users"
USERID=$(id -u $SEEDUSER)
GRPID=$(id -g $SEEDUSER)
echo $USERID > "/opt/seedbox/variables/userid"
echo $GRPID > "/opt/seedbox/variables/groupid"
DOMAIN=$(whiptail --title "Votre nom de Domaine" --inputbox \
"Merci de taper votre nom de Domaine (exemple: nomdedomaine.fr) :" 7 50 3>&1 1>&2 2>&3)
echo $DOMAIN > "/opt/seedbox/variables/domain"
CONTACTEMAIL=$(whiptail --title "Adresse Email" --inputbox \
"Merci de taper votre adresse Email :" 7 50 3>&1 1>&2 2>&3)
echo $CONTACTEMAIL > "/opt/seedbox/variables/mail"
GROUPE=$(cat /opt/seedbox/group)
echo $GROUPE > "/opt/seedbox/variables/group"
pass=$(cut -d ' ' -f2 /opt/seedbox/passwd/login)
echo $pass > /opt/seedbox/variables/pass
echo -e "${CCYAN} * Utilisateur${CEND}"="${BWHITE}$SEEDUSER${CEND}"
echo -e "${CCYAN} * Groupe${CEND}"="${BWHITE}$GROUPE${CEND}"
echo -e "${CCYAN} * Mail${CEND}"="${BWHITE}$CONTACTEMAIL${CEND}"
echo -e "${CCYAN} * Mot de passe${CEND}"="${BWHITE}$pass${CEND}"
echo -e "${CCYAN} * Domaine${CEND}"="${BWHITE}$DOMAIN${CEND}"
checking_errors $?
echo ""

## Mise en variables des remotes
REMOTE=$(grep -iC 4 "token" /root/.config/rclone/rclone.conf | head -n 1 | sed "s/\[//g" | sed "s/\]//g")
REMOTEPLEX=$(grep -iC 2 "/mnt/plexdrive" /root/.config/rclone/rclone.conf | head -n 1 | sed "s/\[//g" | sed "s/\]//g")
REMOTECRYPT=$(grep -v -e $REMOTEPLEX -e $REMOTE /root/.config/rclone/rclone.conf | grep "\[" | sed "s/\[//g" | sed "s/\]//g" | head -n 1)
echo $REMOTEPLEX > /opt/seedbox/variables/remoteplex
echo $REMOTECRYPT > /opt/seedbox/variables/remote

#modification du fichier resume
rm /home/$SEEDUSER/resume > /dev/null 2>&1

# rename actifs containers
echo -e "${BLUE}### Changement de nom des Containers ###${NC}"
docker ps --format '{{.Names}}' > /home/$SEEDUSER/list
for line in $(cat /home/$SEEDUSER/list | cut -d '-' -f1)
do

if [ "$line" != "traefik" ] && [ "$line" != "portainer" ] && [ "$line" != "watchtower" ]; then
echo $line.$DOMAIN >> /home/$SEEDUSER/resume
	if [ "$line" = "nginx" ] || [ "$line" = "mariadb" ] || [ "$line" = "php5" ] || [ "$line" = "php7" ] || [ "$line" = "phpmyadmin" ]; then
	cp /opt/seedbox-compose/includes/webserver/$line.yml /opt/seedbox/conf/$line.yml
	else
	cp /opt/seedbox-compose/includes/dockerapps/$line.yml /opt/seedbox/conf/$line.yml
	fi
docker rename $line-$SEEDUSER $line
fi
done
checking_errors $?
echo ""

#Supression des variables
rm /home/$SEEDUSER/list > /dev/null 2>&1
rm /opt/seedbox/group > /dev/null 2>&1
rm /opt/seedbox/plex.pt > /dev/null 2>&1
rm /opt/seedbox/ports.pt > /dev/null 2>&1
rm /opt/seedbox/ports1.pt > /dev/null 2>&1
rm /opt/seedbox/ports2.pt > /dev/null 2>&1
rm /opt/seedbox/resume > /dev/null 2>&1
rm /opt/seedbox/users > /dev/null 2>&1

# stop rclone
service rclone-$SEEDUSER stop > /dev/null 2>&1
systemctl disable rclone-$SEEDUSER > /dev/null 2>&1

#stop unionfs
service unionfs-$SEEDUSER stop > /dev/null 2>&1
systemctl disable unionfs-$SEEDUSER > /dev/null 2>&1

echo -e "${BLUE}### Installation mergerfs ###${NC}"
echo ""
ansible-playbook /opt/seedbox-compose/includes/config/roles/unionfs/tasks/main.yml
checking_errors $?
echo ""

echo -e "${BLUE}### Réinstallation rclone ###${NC}"
echo ""
ansible-playbook /opt/seedbox-compose/includes/config/roles/rclone/tasks/main.yml
echo ""
echo -e "${BLUE}### Installation du modt ###${NC}"
echo ""
motd
echo ""
echo -e "${CRED}-------------------------------------------------------${CEND}"
echo -e "${CRED}        Mise à jour effectuée avec succés               ${CEND}"
echo -e "${CRED}-------------------------------------------------------${CEND}"

echo -e "\nAppuyer sur ${CCYAN}[ENTREE]${CEND} pour continuer..."
read -r